Graph Validation
junkerm/specmate pull request #356
Opened 2018-12-17 12:33 UTC by Daedo

Added three new validators:
* Detects inner nodes that only have a single cause
* Detects nodes with contradictory causes
* Detects circular causes
Added Set & Array utility functions

2018-12-18 11:06 UTC, sebeder requested changes
It's fine from a technical point of view - However, the code in the validators is quite long. Could you refactor this into smaller methods (and add comments) to increase readability?

2019-03-01 06:55 UTC, sebeder requested changes
Please resolve the merge conflicts as well.

2019-03-01 06:55 UTC, sebeder commented on web/src/app/validation/ceg/contradictory-condition-validator.ts
> +                        let cause = this.topoNodes[key].node;
Change `let` to `const`, since the values are not changed anymore.

2019-03-01 06:55 UTC, sebeder commented on web/src/app/validation/ceg/contradictory-condition-validator.ts
> +        let out = {};
Also here, you can use `const` instead of `let` - please review your code regarding the use of `let` and `const`.

2019-03-01 06:55 UTC, sebeder commented on web/src/app/validation/ceg/contradictory-condition-validator.ts
> +    private _setWasFilled: boolean;
We usually do not use underscores for private variables. You can remove it here as well.

2019-03-15 09:59 UTC, sebeder requested changes
I still think the validation code is complicated and hard to understand. Could you refactor it a little (break it up in single/smaller methods)? In addition to this, we cannot merge this right now, since we are in the middle of a testing phase and I don't want to jeopardize this.

2019-03-18 14:28 UTC, Daedo commented
I have done some further simplification. But I'm still not fully happy with the contradiction test. If you'd have any suggestions I'd be open for those.

2019-03-19 08:29 UTC, sebeder requested changes
Just one more thing:
- Please add translations to error messages.

Then, feel free to merge.

2019-03-20 10:00 UTC, sebeder approved these changes

2019-03-20 10:20 UTC, merged